basic:
  flask:
    options:
      DEBUG: True
  site:
    title: Tony!0
    baseurl: ''
  db:
    global:
      tableprefix: ''
ip:
  maxaddnum: 256
  allow:
    global: true
    private: true
    multicast: False
    loopback: False
    linklocal: False
    reserved: true
  lists:
    whitelist: true
    blacklist: true
defaults:
  wlbl:
    devmode: true
    client:
      newallowed: True
      defaults:
        connectiontype: 0
        maxrange: 32
    upload:
      type: 0
      text:
        type: 0
        title: 'Note'
        allowblanktitle: False
    shortstrlen: 100

api:
  enabled: True
  specdir: '.'
  specs:
    base:
      filename: 'spec.yaml'
      basepath: '/'
      strictvalidation: True
    dev:
      filename: 'devspec.yaml'
      basepath: '/dev'
      strictvalidation: True
  flask:
    host: '127.0.0.1'
    port: 7175
    debug: true

webapp:
  enabled: False
  flask:
    host: '127.0.0.1'
    port: 8008
    debug: true
